### ISSUE TITLE
IAM support seems to have broken for me

### ISSUE THREAD

**Issue by miked63017** [seporaitis/yum-s3-iam#31]
Not sure maybe I am missing a step here, this used to work for me but now with a new 3ec2 instance, new role, and new bucket it no longer works.

For troubleshooting purposes I created the role/policy as:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": "*"
        }
    ]
}
```
aws s3 cli tools work with no need to give keys, they use IAM fine and work for every url I have tried.

So what can I do to troubleshoot this and figure out whats going on?

**Comment by miked63017** [comment]
Oh, by the way this is the error I get:
failure: repodata/repomd.xml from $MYBUCKETNAME: [Errno 256] No more mirrors to try.

Where $MYBUCKETNAME obviously is my bucket name in the output. If I make that file publicly accessible, it then chokes on the next file, one of the sqlite gzipped dbs, with the same error. So in my mind that would mean its not a path mismatch problem. Its probably something simple I am missing, please help me diagnose the problem.

**Comment by asedge** [comment]
What region are you in?  This plugin only supports SigV2 but some regions only support SigV4: http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html.  Also, would you mind sharing your yum repo conf?

**Comment by revmischa** [comment]
I use the configuration specified from https://github.com/revmischa/udo
I'm in us-west-2 (Oregon)
