### ISSUE TITLE
s3iam.py does not honour yum proxy setting

### ISSUE THREAD

**Issue by earsdown** [seporaitis/yum-s3-iam#39]
When I install and activate yum-cron on a system that must use a proxy to access yum repositories, any repositories configured with s3_enabled triggers a stack trace, which points at line 197 in s3iam.py. Looking at firewall logs, I can also confirm the server is trying to connect directly to an S3 IP address, rather than the web proxy.

Yum supports specifying a proxy server in `/etc/yum.conf`. See [this link](https://wiki.centos.org/TipsAndTricks/YumAndRPM#head-ea1fc5d78f578114f4843e57627ebae9cc4fcb5a) for more on this.

A workaround is to modify the cron job to source another file containing http_proxy/https_proxy settings, but it would be good to have this bug fixed, ideally by ensuring the s3iam plugin honours the global and/or repo-specific proxy setting from yum.

**Comment by mbrossard** [comment]
Currently, the plugin doesn't support proxy servers.

**Comment by Cinderhaze** [comment]
A workaround as referenced from https://github.com/jbraeuer/yum-s3-plugin/pull/10#issuecomment-93567106

you should be able to define the proxy information in /etc/boto.cfg

**Comment by AgarFu** [comment]
The  https://github.com/seporaitis/yum-s3-iam/pull/58 implements support for proxy

**Comment by mbrossard** [comment]
Fixed by @AgarFu in #58
