### ISSUE TITLE
Getting 403 Access Forbidden when accessing repomd.xml

### ISSUE THREAD

**Issue by dhisaxen** [seporaitis/yum-s3-iam#42]
The exact error I am getting is this:
Error: Cannot retrieve repository metadata (repomd.xml) for repository: samplerepo. Please verify its path and try again

I did some logging and found that the request to get the repomd file is getting rejected. HTTP Error 403: Forbidden 

I see that the S3 URL is all ok. https://bucket-name.s3.amazonaws.com/path/to/samplerepo/repodata/repomd.xml

All the other values such as access key secret key and the token are getting its values as well.

**Comment by dhisaxen** [comment]
After a deeper logging and understanding I realized that if the x-amz-security-token tag is removed and  the account credentials are taken, it works all ok. Probably there is some issue with the way tag has to be defined or is changed as per AWS API.

**Comment by sbkg0002** [comment]
Can you explain how to remove the tag? I'm running into the same problem.

**Comment by dhisaxen** [comment]
Its been a long time I worked on this, try commenting token in the get_credentials method Or you may try commenting directly in the signV4 method. Hope it helps!
