### ISSUE TITLE
fails to work in cn-north-1

### ISSUE THREAD

**Issue by tscanlon** [seporaitis/yum-s3-iam#51]
I was trying to get this to run in our AWS China deployment and was unable to get it to work. 

I tried setting the the region, bucket and path and the url they combine into manually to `cn-north-1, mybucket, /` and combine them into `https://s3.cn-north-1.amazonaws.com.cn/mybucket/` and it failed. The real way would be to have the regex handle it properly but I was just trying to get something working quick.

Sadly I was in the middle of firefighting several issues and had to stop troubleshooting this as I had a faster way out of my immediate problems. 

I'd love to contribute a PR to make it work in china but I may need a little more guidance / help on debugging, or I might just need more sleep. I'm able to test anyones changes if you get to it faster than I do.

Its been super helpful in our non-china deployments, so thanks for your work. 

edit: http://docs.amazonaws.cn/en_us/general/latest/gr/rande.html#s3_region aws china is special and more akin to aws gov cloud. It has unique endpoints and discrete iam from the normal aws. tl;dr its a pain.

**Comment by mbrossard** [comment]
Could you look at the aws-cn branch to see if this gets you closer to a solution?

**Comment by tscanlon** [comment]
Thanks for the timely response and sorry mine, is so delayed. Works like a charm for me.

**Comment by mbrossard** [comment]
@tscanlon: thank you for your test. I released the version you tested as v1.1.1. If it stops working in future version or because AWS changes something, tell us about it.
