### ISSUE TITLE
Rename to yum-s3-iam-plugin

### ISSUE THREAD

**Issue by nkadel-skyhook** [seporaitis/yum-s3-iam#54]
Since the tools are for a yum plugin, the package should be named yum-s3-iam-plugin.

**Comment by mbrossard** [comment]
Hi,

It could also be named yum-plugin-s3-iam. It's a good idea but I'm concerned that changing the name would cause a lot of issue for existing users. Are there any technical issues caused by the naming used?

Sincerely,
Mathias
