### ISSUE TITLE
Problems using IAM role

### ISSUE THREAD

**Issue by bendavies** [seporaitis/yum-s3-iam#57]
Hey there!

I'm trying to use this plugin (latest master commit) on an EC2 instances, authenticating via IAM role.
The plugin/yum gives this error, however:
```
Error: Cannot retrieve repository metadata (repomd.xml) for repository: foo. Please verify its path and try again
```

The auth/IAM role seems fine, as I can run
```
aws s3 ls s3://bucket-url/path
```
on the instance without problem.

Any idea how i might debug the issue?
I was looking at the plugin to see if i could enable logging, but no such luck.

Thanks!

**Comment by mbrossard** [comment]
Hi,

I missed this message. Can you tell us the URL you've used in the configuration? Have you tried the different URL forms? Some regions need to use v4 signature and for that we need to know the region.

**Comment by bendavies** [comment]
Hey @mbrossard. Thanks for the reply! I'll give this a try again this week. It's been a while!

**Comment by bendavies** [comment]
@mbrossard btw, what URL forms do you suggest I try? Thanks!

**Comment by mbrossard** [comment]
Try the path-style URL: `https://s3-<aws-region>.amazonaws.com/<bucket>/<path>`
If the S3 bucket is in us-east-1 region, you have to use `https://s3.amazonaws.com/<bucket>/<path>`

The region in the URL always refers to the region where the bucket is located.

**Comment by mchodson** [comment]
I have the same issue. If I add aws credentials to my ec2 instance this works fine. but if i use iam role i get "The requested URL returned error: 403 Forbidden".

**Comment by mbrossard** [comment]
In both cases you can check that using the instance profile (or the same credentials used in the configuration):

`aws s3 cp s3://<bucket>/<path>/repodata/repomd.xml .`

**Comment by bendavies** [comment]
apologies @mbrossard, i still mean to look at this. I'm just super busy right now.

**Comment by bendavies** [comment]
hey there again @mbrossard,
I've just started looking at this again.

It seems i can now install via the plugin, (for some unknown reason, i've changed nothing), but the following doesn't work.
```
yum --disablerepo "*" --enablerepo "foo" list available
Loaded plugins: fastestmirror, presto, s3iam, security
Loading mirror speeds from cached hostfile
```
no packages are listed, but they are there!
Any ideas?

Thanks

**Comment by bendavies** [comment]
ok, i'm an idiot :-) 
`list available` won't list currently installed packages.

I think we're good!
