### ISSUE TITLE
Special value "_none_" for repository proxy is not handled correctly

### ISSUE THREAD

**Issue by andlam** [seporaitis/yum-s3-iam#59]
Hello,

Configuring a RPM repository with the special value `_none_` for its proxy is not handled correctly. The plugin is using `_none_` as proxy and fails resolving it as a proxy FQDN.

As a result, the retrieval of the IAM credentials fails.

According to man(5) yum.conf, that value indicates that NO proxy should be used in the requests made to that repository.

> proxy URL to the proxy server for this repository. Set to `'_none_'` to disable the global proxy setting for this repository. If this is unset it inherits it from the global setting

Here is a patch that fixes the issue:

```
--- s3iam.py	2017-08-18 18:56:33.000000000 +0000
+++ s3iam.py.fixed	2017-08-22 07:14:22.746504644 +0000
@@ -168,7 +168,8 @@
         if 'http_proxy' in os.environ:
             proxy_config['http'] = os.environ['http_proxy']
         if repo.proxy:
-            proxy_config['https'] = proxy_config['http'] = repo.proxy
+            if repo.proxy != '_none_':
+                proxy_config['https'] = proxy_config['http'] = repo.proxy
         if proxy_config:
             proxy = urllib2.ProxyHandler(proxy_config)
             opener = urllib2.build_opener(proxy)
```

We would appreciate if a fix could be included ASAP.

Thank you very much!

**Comment by andlam** [comment]
It seems that the fix that got merged contains two underscores 

    if repo.proxy and repo.proxy != '__none__':
        proxy_config['https'] = proxy_config['http'] = repo.proxy

whereas the fix that got posted (and is in production use) contains only one underscore

    proxy_config['https'] = proxy_config['http'] = repo.proxy
        if repo.proxy != '_none_':
            proxy_config['https'] = proxy_config['http'] = repo.proxy

Is there a reason for that or is it just an oversight?

**Comment by mbrossard** [comment]
I looked at the yum documentation (https://linux.die.net/man/5/yum.conf) and based my change on that. It seem to be consistent with the [source code](https://github.com/rpm-software-management/yum/blob/master/yum/config.py#L222).

**Comment by andlam** [comment]
Hello Mathias,


Ø  I looked at the yum documentation (https://linux.die.net/man/5/yum.conf) and based my change on that. It seem to be consistent with the source code<https://github.com/rpm-software-management/yum/blob/master/yum/config.py#L222>

In the YUM source code, there are single underscores appended / prepended to “none”:        if url.lower() == '_none_':

At line 170 in s3iam.py, there are double underscores appended / prepended to “none”: if repo.proxy and repo.proxy != '__none__':

Kind regards / Mit freundlichen Grüßen

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Andre Lammel
[cid:65F58D67-581F-46EE-882D-87A316C110C5]
Direct: +49 911 9269 9125
Mobile +49 172 6625 351

Nasdaq Germany GmbH. Geschäftsführer: Gabriella Halasz-Clarke und Martin Schmidt. Sitz der Gesellschaft: Leipzig. Registergericht: Amtsgericht Leipzig, HRB 29262.
