### ISSUE TITLE
Link to instructions is dead.

### ISSUE THREAD

**Issue by schaden-fred** [seporaitis/yum-s3-iam#81]
In README.md, the link under "How do I set it up?" is dead, because Jeremy Carroll's site is offline.  I'd love to use this tool, but there's no instructions anymore.

**Comment by mbrossard** [comment]
Well that's not great. The domain seems to be parked. If someone has a copy of the blog's content, I'd be able to put it in the repository.

It should be as easy as addding `s3_enabled=1` to your `.repo` file as in
https://github.com/seporaitis/yum-s3-iam/blob/master/s3iam.repo

**Comment by dyoum117** [comment]
https://web.archive.org/web/20160814201430/http://www.carrollops.com/blog/2012/09/11/s3-yum-repos-with-iam-authorization/

Here is a snapshot that seems to contain what you guys are looking for. Maybe the contents can be copied onto a separate instructions txt file for this repo.

**Comment by seporaitis** [comment]
#86 added a link to the wayback machine record of the post.
